/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CreateUpdateModal: typeof import('./components/CreateUpdateModal.vue')['default']
    DeletePerson: typeof import('./components/DeletePerson.vue')['default']
    EditPerson: typeof import('./components/EditPerson.vue')['default']
    PersonTable: typeof import('./components/PersonTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
